smtp_server:
    host: localhost
    port: 1025

dev_smtp_server:
    host: localhost
    port: 1025

submission_email:
    subject: Online SF2 created for project '{project_id}'
    body: |
        Dear Customer,

        An Online SF2 form has been submitted for project '{project_id}'.  You can find the form at the following url:

        {sf2_url}

        Please do not hesitate to contact us if you need any assistance completing the form.

        Best wishes,

        Edinburgh Genomics
    sender: 
        name: Online SF2 Project Setup
        address: online-sf2-project-setup@edinburgh-genomics.ed.ac.uk
    recipient: 
        name: Edinburgh Genomics Admin
        address: genepool-admin@ed.ac.uk

reissue_email:
    subject: Online SF2 reissued for project '{project_id}'
    body: |
        Dear Customer,

        An Online SF2 form has been reissued for project '{project_id}'.  You can find the form at the following url:

        {sf2_url}

        Please do not hesitate to contact us if you need any assistance completing the form.

        Best wishes,

        Edinburgh Genomics
    sender: 
        name: Online SF2 Project Setup
        address: online-sf2-project-setup@edinburgh-genomics.ed.ac.uk
    recipient: 
        name: Edinburgh Genomics Admin
        address: genepool-admin@ed.ac.uk
